apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: kustomize-app
  namespace: argocd
spec: 
  destination: 
    namespace: kustomize-app
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: kustomize-guestbook
    repoURL: "https://github.com/mopurideepa/argocd-example-apps.git"
    targetRevision: main
    kustomize:
      version: v3.5.4
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
