apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deepa3
  namespace: argocd
spec:
  destination:
    namespace: deepa3
    server: "shttps://kubernetes.default.svc"
  project: default 
  source: 
    path: app
    repoURL: "https://github.com/mopurideepa/argocd-example-apps.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
