apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deepa-dev-project
  namespace: argocd
spec:
  destination:
    namespace: ns-1
    server: "https://kubernetes.default.svc"
  project: dev-project
  source: 
    path: application-namespace
    repoURL: "https://github.com/mopurideepa/argocd-example-apps.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
